//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int loanID { get; set; }
        public string loanCreditor { get; set; }
        public double loanPrincipal { get; set; }
        public int loanTerm { get; set; }
        public double loanInterest { get; set; }
        public double loanTotal { get; set; }
        public double loanAmountPaid { get; set; }
        public byte[] loanDT { get; set; }
        public int userID { get; set; }
    
        public virtual user user { get; set; }
    }
}
