//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactID { get; set; }
        public string transactType { get; set; }
        public string transactName { get; set; }
        public double transactAmount { get; set; }
        public byte[] transactDT { get; set; }
        public int userID { get; set; }
    
        public virtual user user { get; set; }
    }
}
